### ISSUE TITLE
Create commhack-2020 website

### ISSUE THREAD

**Issue by fhopp** [ica-hack/commhack-site#8]
We briefly touched on this, but I think it is a great idea for dissemination and resources. Since many people will be unfamiliar with the concept and structure, the website can be a centralized hub for information, organization (e.g, project and break-out proposals), and other resources (e.g., the PNAS paper on hackathons). I'd suggest a simple page with github pages will do. I definitely recommend against creating a github repo with info, because this might already shy away some folks.

**Comment by jacobtfisher** [comment]
Initial site has been made and is being deployed as we speak. Here is the screenshot.
<img width="1385" alt="Screen Shot 2019-10-13 at 11 58 52 AM" src="https://user-images.githubusercontent.com/21992882/66720423-5609fc00-edb1-11e9-922b-676cdd102dd5.png">

**Comment by jacobtfisher** [comment]
Initial deploy is live https://quirky-villani-f567d2.netlify.com/

We obviously need a lot more content, but I think the framework is good. Feedback welcomed!
